### PR TITLE
Support for updated python-single-r1.eclass

### PR DESCRIPTION
**Pull request by mgorny**
Note: I expect tests to fail, I'm abusing your CI ;-).

### CODE REVIEW

**Comment by radhermit** [comment]
> Note: I expect tests to fail, I'm abusing your CI ;-).

That's fine, but I don't think I've enabled CI for PRs yet. I'll try to do that today.

**Comment by mgorny** [comment]
It's kinda curious because I got some CI mail about failure. But maybe it's getting enabled automatically on my fork or w/e.

**Comment by radhermit** [comment]
Now it should if you re-push.

**Comment by mgorny** [comment]
Ok, it seems to be good now. If you could release it ASAP, that would be awesome. This is needed for gentoo/gentoo#14589.

**Comment by radhermit** [comment]
Thanks, merged.

Also, at some point it would be nice if you could add ebuilds that trigger the related results to a repo in tests/repos along with the expected output and patches to fix them.

**Pull request closed without merging**
