### PR TITLE
contrib/emacs: add flycheck-pkgcheck.el - Flycheck checker for ebuilds

### PR DESCRIPTION
**Pull request by xgqt**
Bug: https://github.com/pkgcore/pkgcheck/issues/417

Signed-off-by: Maciej Barć <xgqt@gentoo.org>

### CODE REVIEW

**Comment by thesamesam** [comment]
Please cherry pick Arthur's commit as he suggested as well.

**Comment by xgqt** [comment]
Right, it was supposed to be the commit to master, my bad.

**Comment by xgqt** [comment]
Switched to `master`. Arthurzam's commit is there too.

**Review by arthurzam — APPROVED** [review]
Thank you, I'm merging it 😄 
Now, please do the changes to `pkgcheck-9999` and open a PR on `::gentoo` (note, this is so I can just do small review this looks nice and good, cause the changes you mentions with compiling lisp are unknown for me, so I can't do it myself).

Thank you for improving for all emacs users (even though I'm from vim camp 😉  )

**Comment by xgqt** [comment]
Oh! I realized just now that there is a problem - app-emacs/flycheck is keyworded only on ~amd64.
This will not affect the live version but for keyworded/stabilized releases this is bad.
But Flycheck should actaually be "allarches" but the GNU Emacs team haven't field any bugs to keyword it yet (which I blame myself for :/).

**Comment by arthurzam** [comment]
@xgqt So, some solutions for now:

1. As you said, to keyword on arches - good idea, but maybe not all arches want this dep tree (like hppa or sparc or ia64 or mips)
2. Mask everywhere the use flag, and unmask on amd64 and other arches that are ready.
3. About the stable/unstable, we can mask the flag for stable profiles, but preferably unmask it soon (so stable pkgcheck users can use emacs integration).

**Pull request merged**
